name: Merge Branches and Create New Branch

on:
  workflow_dispatch:
    inputs:
      branch1:
        description: 'First branch to merge'
        required: true
        default: 'specific-avatar-branch'
      branch2:
        description: 'Second branch to merge'
        required: true
        default: 'specific-room-branch'
      new_branch:
        description: 'new branch name'
        required: true
        default: 'hoge'

jobs:
  merge-and-create:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch
      run: git fetch origin

    - name: Pull latest changes
      run: git checkout ${{ github.event.inputs.branch1 }} && git pull origin ${{ github.event.inputs.branch1 }}

    - name: Append _hoge to new_branch
      run: echo "new_branch_with_suffix=${{ github.event.inputs.new_branch }}-2d-photo-branch" >> $GITHUB_ENV
    
    - name: Create and merge branches
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git checkout 
        git checkout ${{ github.event.inputs.branch1 }}
        git pull
        git checkout ${{ github.event.inputs.branch2 }}
        git pull
        git checkout -b ${{ env.new_branch_with_suffix }} ${{ github.event.inputs.branch1 }}
        git merge ${{ github.event.inputs.branch2 }} --no-ff -m "Merge ${{ github.event.inputs.branch2 }} into ${{ env.new_branch_with_suffix }}" || true
        git push origin ${{ env.new_branch_with_suffix }}

    #- name: Notify Slack
     # if: success()
     # run: |
       # curl -X POST -H 'Content-type: application/json' --data '{"text":"New branch `${{ env.new_branch }}` created successfully by merging `${{ github.event.inputs.branch1 }}` and `${{ github.event.inputs.branch2 }}`."}' $SLACK_WEBHOOK_URL
